USE [master]
GO
/****** Object:  Database [Orion]    Script Date: 12/22/2021 7:56:39 PM ******/
CREATE DATABASE [Orion]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Orion', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Orion.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Orion_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Orion_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Orion] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Orion].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Orion] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Orion] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Orion] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Orion] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Orion] SET ARITHABORT OFF 
GO
ALTER DATABASE [Orion] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Orion] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Orion] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Orion] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Orion] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Orion] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Orion] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Orion] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Orion] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Orion] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Orion] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Orion] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Orion] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Orion] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Orion] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Orion] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Orion] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Orion] SET RECOVERY FULL 
GO
ALTER DATABASE [Orion] SET  MULTI_USER 
GO
ALTER DATABASE [Orion] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Orion] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Orion] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Orion] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Orion] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Orion] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Orion', N'ON'
GO
ALTER DATABASE [Orion] SET QUERY_STORE = OFF
GO
USE [Orion]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 12/22/2021 7:56:39 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 12/22/2021 7:56:39 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](450) NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[DeletedAt] [datetime2](7) NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ContractEdits]    Script Date: 12/22/2021 7:56:39 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ContractEdits](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ContractId] [int] NOT NULL,
	[Date] [datetime2](7) NOT NULL,
	[Status] [int] NOT NULL,
	[TotalPrice] [decimal](18, 2) NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[DeletedAt] [datetime2](7) NULL,
 CONSTRAINT [PK_ContractEdits] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[contractPackages]    Script Date: 12/22/2021 7:56:39 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[contractPackages](
	[ContractId] [int] NOT NULL,
	[PackageId] [int] NOT NULL,
 CONSTRAINT [PK_contractPackages] PRIMARY KEY CLUSTERED 
(
	[ContractId] ASC,
	[PackageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Contracts]    Script Date: 12/22/2021 7:56:39 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contracts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Date] [datetime2](7) NOT NULL,
	[Username] [nvarchar](max) NOT NULL,
	[Duration] [int] NOT NULL,
	[Discount] [int] NULL,
	[FreeMonths] [int] NULL,
	[Status] [int] NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[DeletedAt] [datetime2](7) NULL,
 CONSTRAINT [PK_Contracts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Packages]    Script Date: 12/22/2021 7:56:39 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Packages](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](450) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[Price] [decimal](18, 2) NOT NULL,
	[CategoryId] [int] NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[DeletedAt] [datetime2](7) NULL,
 CONSTRAINT [PK_Packages] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Categories_Name]    Script Date: 12/22/2021 7:56:39 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Categories_Name] ON [dbo].[Categories]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_ContractEdits_ContractId]    Script Date: 12/22/2021 7:56:39 PM ******/
CREATE NONCLUSTERED INDEX [IX_ContractEdits_ContractId] ON [dbo].[ContractEdits]
(
	[ContractId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_contractPackages_PackageId]    Script Date: 12/22/2021 7:56:39 PM ******/
CREATE NONCLUSTERED INDEX [IX_contractPackages_PackageId] ON [dbo].[contractPackages]
(
	[PackageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Packages_CategoryId]    Script Date: 12/22/2021 7:56:39 PM ******/
CREATE NONCLUSTERED INDEX [IX_Packages_CategoryId] ON [dbo].[Packages]
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Packages_Name]    Script Date: 12/22/2021 7:56:39 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Packages_Name] ON [dbo].[Packages]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ContractEdits]  WITH CHECK ADD  CONSTRAINT [FK_ContractEdits_Contracts_ContractId] FOREIGN KEY([ContractId])
REFERENCES [dbo].[Contracts] ([Id])
GO
ALTER TABLE [dbo].[ContractEdits] CHECK CONSTRAINT [FK_ContractEdits_Contracts_ContractId]
GO
ALTER TABLE [dbo].[contractPackages]  WITH CHECK ADD  CONSTRAINT [FK_contractPackages_Contracts_ContractId] FOREIGN KEY([ContractId])
REFERENCES [dbo].[Contracts] ([Id])
GO
ALTER TABLE [dbo].[contractPackages] CHECK CONSTRAINT [FK_contractPackages_Contracts_ContractId]
GO
ALTER TABLE [dbo].[contractPackages]  WITH CHECK ADD  CONSTRAINT [FK_contractPackages_Packages_PackageId] FOREIGN KEY([PackageId])
REFERENCES [dbo].[Packages] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[contractPackages] CHECK CONSTRAINT [FK_contractPackages_Packages_PackageId]
GO
ALTER TABLE [dbo].[Packages]  WITH CHECK ADD  CONSTRAINT [FK_Packages_Categories_CategoryId] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Categories] ([Id])
GO
ALTER TABLE [dbo].[Packages] CHECK CONSTRAINT [FK_Packages_Categories_CategoryId]
GO
USE [master]
GO
ALTER DATABASE [Orion] SET  READ_WRITE 
GO
